# Generated by Django 5.0.1 on 2024-01-06 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='otp',
            field=models.CharField(default=1111, max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='election',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
