# Generated by Django 5.0.1 on 2024-01-06 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0002_voter_otp_alter_election_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='otp',
            field=models.CharField(max_length=100),
        ),
    ]
