# Generated by Django 5.0.1 on 2024-01-06 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0003_alter_voter_otp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vote',
            new_name='Subscribe',
        ),
        migrations.AlterUniqueTogether(
            name='subscribe',
            unique_together={('election', 'voter')},
        ),
    ]
