# Generated by Django 5.0.1 on 2024-01-06 06:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voteapp", "0005_remove_candidate_name_candidate_picture_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BatchEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fichier",
                    models.FileField(
                        upload_to="documents/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["csv", "xls", "xlsx"],
                                message="Seuls les fichiers CSV, Excel (XLS, XLSX) sont autorisés.",
                            )
                        ],
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="candidate", unique_together={("election", "first_name", "last_name")},
        ),
    ]
