# Generated by Django 5.0.1 on 2024-01-06 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("voteapp", "0006_batchemail_alter_candidate_unique_together"),
    ]

    operations = [
        migrations.RemoveField(model_name="voter", name="is_valid",),
    ]
